# GitHub Sponsors & Funding Options
# https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

github: ayyazahmad
patreon: ayyazahmad
ko_fi: ayyazahmad
custom:
  - https://azad.co/donate
  - https://wise.com/pay/recipient/your-wise-id
